name: Deploy V62 (disabled)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "Le workflow V62 est obsolète. Utiliser Deploy V63."
